### ISSUE TITLE
[wanted]Looking for collaborators

### ISSUE THREAD

**Issue by anharu2394** [anharu2394/tapioca#10]
now, Due to studying for college entrance exams(Feb 2022),  I can not manage the repository.
I want to develop the repo to add new features after finishing the exam.
Please manage the repo while i am studying for this.
Could you manage the repo?
Are there someone to manage it?

**Comment by tokku5552** [comment]
I've never contributed, can I become an collaborator?
This is the level of Flutter.
https://github.com/tokku5552/TODOAppSample-Flutter
I will contact you in Japanese via Twitter DM.

**Comment by anharu2394** [comment]
Thank you.
I will add you to collaborators🎉🎉

**Comment by Gorter-dev** [comment]
If possible I also would like to contribute once in a while. Due to work I don't have a lot of spare time, but I can contribute once in a while.

**Comment by Jartz** [comment]
@anharu2394  I want to collaborate, I am currently using your library to create a feature in my application. could you add me

**Comment by anharu2394** [comment]
@Jartz , Thank you, welcome.

**Comment by Jartz** [comment]
@anharu2394  thank you, i'm working in allow to add multiple same type And merge sound. soon I'll be uploading PR

**Comment by anharu2394** [comment]
@Jartz I recommend creating the issue about the feature you're developing to you.

**Comment by fernandocruz** [comment]
Hey @anharu2394, I would love collaborate with your project. Could you add me?

**Comment by anharu2394** [comment]
@fernandocruz sure

**Comment by Baneeishaque** [comment]
i want to style the overlay text, is it already available?
i am planning to develop this feature - it will be better, if you add me as collaborator.

**Comment by anharu2394** [comment]
@Baneeishaque sure
