### ISSUE TITLE
tapioca not work on android 10 i can't get it please help the error is "video_proccessing_error"

### ISSUE THREAD

**Issue by programmermasrawy** [anharu2394/tapioca#15]

**Comment by programmermasrawy** [comment]
@anharu2394 do you have any solution about that ?

**Comment by Jartz** [comment]
@programmermasrawy  hey man, can you check feature/multiple-text-overlay.

**Comment by programmermasrawy** [comment]
> @programmermasrawy hey man, can you check feature/multiple-text-overlay.

ok i solve it by making the image bytedate codec in png , thank you :)
