### ISSUE TITLE
error: initializer for conditional binding must have Optional type, not 'AVAssetTrack'

### ISSUE THREAD

**Issue by pbwauyo** [anharu2394/tapioca#21]
I get the following error when I run on Xcode 12.3.0, Flutter 2.0.0, tapioca ^1.0.1
```
/Users/distiller/flutter/.pub-cache/hosted/pub.dartlang.org/tapioca-1.0.1/ios/Classes/VideoGeneratorService.swift:20:11: error: initializer for conditional binding must have Optional type, not 'AVAssetTrack'
        guard let videoTrack:AVAssetTrack = vtrack[0] else {
```

**Comment by tokku5552** [comment]
@pbwauyo 
Thank you for reporting the bug!
Looking at the error may be a null-safty related issue
Is it possible to lower the version of Flutter and try it?

**Comment by anharu2394** [comment]
maybe, the issue have already resolved by #5 .
So, we should publish updates.
@tokku5552

**Comment by tokku5552** [comment]
@anharu2394 
Ok.
The develop branch still has problems, but I think the master branch is okay, so would you like to publish it as 1.0.2?
In the current state.

**Comment by anharu2394** [comment]
@tokku5552 Exactly.
Publish the master branch as 1.0.2, please.
Thanks.

**Comment by anharu2394** [comment]
(By the way, we should merge the develop branch into the master branch later.)
