### ISSUE TITLE
Initializer for conditional binding must have optional type, not AVAssetTrack

### ISSUE THREAD

**Issue by Gorter-dev** [anharu2394/tapioca#4]
File: VideoGeneratorService.swift
Line: 20

**Comment by Gorter-dev** [comment]
Fix

Change:

guard let videoTrack:AVAssetTrack = vtrack[0] else {

into 

guard let videoTrack: AVAssetTrack = vtrack[0] as AVAssetTrack? else {

**Comment by anharu2394** [comment]
Thank you.
