### ISSUE TITLE
[Request] Any solution for stream media?

### ISSUE THREAD

**Issue by ryuujo1573** [anharu2394/tapioca#66]
Hi, I was wondering: **is `tapioca` capable for live video processing?**

Such as filtering video data from local camera directly etc..
// camera input comes in the form of buffer object

**Comment by anharu2394** [comment]
Currently,  Tapioca disables to process videos on live stream. 
But,  Flutter UI can filter video data from local camera directly.
If you want to attach color filter, you can use this https://api.flutter.dev/flutter/widgets/ColorFiltered-class.html . And then, you will process videos not on live stream.
Thanks.
