### ISSUE TITLE
'onRequestPermissionsResult' overrides nothing

### ISSUE THREAD

**Issue by suryanadiminti99** [anharu2394/tapioca#70]
C:\Users\user\Downloads\tapioca-master\tapioca-master\android\src\main\kotlin\me\anharu\video_editor\VideoEditorPlugin.kt: (27, 8): Class 'VideoEditorPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: C:\Users\user\Downloads\tapioca-master\tapioca-master\android\src\main\kotlin\me\anharu\video_editor\VideoEditorPlugin.kt: (105, 5): 'onRequestPermissionsResult' overrides nothing

**Comment by fatimaEzzat** [comment]
i have the same issue

**Comment by mhdaslam790** [comment]
i am also facing the same issue

**Comment by chituanh** [comment]
i have the same issue

**Comment by mhdaslam790** [comment]
https://github.com/mhdaslam790/tapioca

You can use it

**Comment by DennisAshford** [comment]
Same issue here.
